#!/bin/bash

bad_usage() {
  echo -e "\nUsage: cms authoring|delivery run|build\n"
  exit 1
}

arrayContainsElement() {
  local element
  for element in "${@:2}"
  do
    [[ "$element" == "$1" ]] && return 0
  done
  return 1
}

VERSION=3.1.5

ops=(run build)
services=(authoring delivery)

if ! arrayContainsElement "$1" "${services[@]}"; then
  bad_usage
fi
if ! arrayContainsElement "$2" "${ops[@]}"; then
  bad_usage
fi

export WRAPPER=true
./_cms.sh $VERSION $@

exit $?

