#!/bin/bash
set -e

usage() {
  echo ""
  echo "Usage: $(basename "$0") INTERFACE CONTEXT command"
  echo ""
  echo "Manages Crafter authoring and delivery images and containers"
  echo ""
  echo "Interfaces:"
  echo "    authoring Manage Crafter authoring images and containers"
  echo "    delivery  Manage Crafter delivery images and containers"
  echo ""
  echo "Contexts:"
  echo "    container Manage Crafter containers for the selected 'interface'"
  echo "    image     Manage Crafter images for the selected 'interface'"
  echo ""
  echo "Run '$(basename "$0") INTERFACE --help' for more information on how to manage an interface."
}

CRAFTER_HOME=${CRAFTER_HOME:=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}
CRAFTER_SCRIPTS_HOME=${CRAFTER_HOME}/scripts
export CRAFTER_HOME
export CRAFTER_SCRIPTS_HOME

case $1 in
authoring | delivery)
  INTERFACE=$1
  export INTERFACE
  CMD_PREFIX="crafter $1"
  export CMD_PREFIX
  if [ -x "${CRAFTER_SCRIPTS_HOME}/${INTERFACE}/interface.sh" ]; then
    # shellcheck disable=SC2068
    "${CRAFTER_SCRIPTS_HOME}/${INTERFACE}/interface.sh" ${@:2}
  else
    # shellcheck disable=SC2068
    "${CRAFTER_SCRIPTS_HOME}/common/interface.sh" ${@:2}
  fi
  ;;
*)
  usage
  exit 1
  ;;
esac
